# Generated by Django 5.1.1 on 2024-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
