# Generated by Django 5.1.1 on 2024-09-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_rename_student_learner_remove_doubt_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='post',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='student',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='doubt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Doubt',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
